name: Build and Release

on:
  push:
    branches: [ main, master ]
    tags:
      - '*'
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Build plugin
      run: npm run build

    - name: Create release package
      run: |
        mkdir -p release
        cp main.js manifest.json versions.json release/
        cd release
        zip -r ../obsidian-canvas-creator-${{ github.sha }}.zip .

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: obsidian-canvas-creator-${{ github.sha }}
        path: |
          main.js
          manifest.json
          versions.json
        retention-days: 30

    - name: Upload release package
      uses: actions/upload-artifact@v4
      with:
        name: obsidian-canvas-creator-release-${{ github.sha }}
        path: obsidian-canvas-creator-${{ github.sha }}.zip
        retention-days: 90

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Build plugin
      run: npm run build

    - name: Create release package
      run: |
        mkdir -p release
        cp main.js manifest.json versions.json release/
        cd release
        zip -r ../obsidian-canvas-creator-${GITHUB_REF#refs/tags/}.zip .

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          main.js
          manifest.json
          versions.json
          obsidian-canvas-creator-*.zip
        draft: false
        prerelease: false
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
